require("dotenv").config();
const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

const employees = [
  { nickname: "Young", email: "youngholee@buzzvil.com" },
  { nickname: "John", email: "john.lee@buzzvil.com" },
  { nickname: "Zune", email: "zuneseo@buzzvil.com" },
  { nickname: "Max", email: "max@buzzvil.com" },
  { nickname: "Steve", email: "steve.jang@buzzvil.com" },
  { nickname: "Bling", email: "bling.kim@buzzvil.com" },
  { nickname: "Brice", email: "brice.bang@buzzvil.com" },
  { nickname: "Jetty", email: "jetty.cho@buzzvil.com" },
  { nickname: "Jerry", email: "jerry.ko@buzzvil.com" },
  { nickname: "Dio", email: "dio.heo@buzzvil.com" },
  { nickname: "Bruce", email: "bruce.kim@buzzvil.com" },
  { nickname: "Kai", email: "kai.lee@buzzvil.com" },
  { nickname: "Ed", email: "ed.kang@buzzvil.com" },
  { nickname: "Clair", email: "clair.baek@buzzvil.com" },
  { nickname: "Lucy", email: "lucy.yoo@buzzvil.com" },
  { nickname: "Justin", email: "justin.jeong@buzzvil.com" },
  { nickname: "Gloria", email: "gloria.lee@buzzvil.com" },
  { nickname: "Benjamin", email: "benjamin.lee@buzzvil.com" },
  { nickname: "Daisy", email: "daisy.kim@buzzvil.com" },
  { nickname: "Olivia", email: "olivia.kim@buzzvil.com" },
  { nickname: "Daniel", email: "daniel.song@buzzvil.com" },
  { nickname: "Nike", email: "nike.moon@buzzvil.com" },
  { nickname: "Thomas", email: "thomas.kim@buzzvil.com" },
  { nickname: "Bella", email: "bella.oh@buzzvil.com" },
  { nickname: "Bernard", email: "bernard.choi@buzzvil.com" },
  { nickname: "Cordelia", email: "cordelia.chang@buzzvil.com" },
  { nickname: "Jackie", email: "jackie.park@buzzvil.com" },
  { nickname: "Jules", email: "jules.yim@buzzvil.com" },
  { nickname: "Dane", email: "dane.kim@buzzvil.com" },
  { nickname: "BK", email: "bk.kang@buzzvil.com" },
  { nickname: "Roha", email: "roha.lee@buzzvil.com" },
  { nickname: "Berry", email: "berry.kim@buzzvil.com" },
  { nickname: "Phil", email: "phil.yoo@buzzvil.com" },
  { nickname: "Cindy", email: "cindy.choi@buzzvil.com" },
  { nickname: "Elle", email: "elle.shin@buzzvil.com" },
  { nickname: "Jua", email: "jua.song@buzzvil.com" },
  { nickname: "Mason", email: "mason.yun@buzzvil.com" },
  { nickname: "Jia", email: "jia.cui@buzzvil.com" },
  { nickname: "Ron", email: "ron.son@buzzvil.com" },
  { nickname: "Toy", email: "toy.yu@buzzvil.com" },
  { nickname: "Marvin", email: "marvin.hong@buzzvil.com" },
  { nickname: "Silva", email: "silva.yun@buzzvil.com" },
  { nickname: "Scott", email: "scott.choe@buzzvil.com" },
  { nickname: "Dean", email: "dean.choi@buzzvil.com" },
  { nickname: "Logan", email: "logan.kim@buzzvil.com" },
  { nickname: "Theo", email: "theo.park@buzzvil.com" },
  { nickname: "Luis", email: "luis.hong@buzzvil.com" },
  { nickname: "Henry", email: "henry.yoon@buzzvil.com" },
  { nickname: "Ella", email: "ella.yoo@buzzvil.com" },
  { nickname: "Kun", email: "kun.kim@buzzvil.com" },
  { nickname: "Freeman", email: "freeman.lee@buzzvil.com" },
  { nickname: "Hazel", email: "hazel.jang@buzzvil.com" },
  { nickname: "Crow", email: "crow.yang@buzzvil.com" },
  { nickname: "Koby", email: "koby.jo@buzzvil.com" },
  { nickname: "Judy", email: "judy.park@buzzvil.com" },
  { nickname: "Jake", email: "jake.moon@buzzvil.com" },
  { nickname: "Derrick", email: "derrick.jung@buzzvil.com" },
  { nickname: "Breeze", email: "breeze.song@buzzvil.com" },
  { nickname: "Van", email: "van.kim@buzzvil.com" },
  { nickname: "Chloe", email: "chloe.kim@buzzvil.com" },
  { nickname: "Wynn", email: "wynn.huh@buzzvil.com" },
  { nickname: "Ivan", email: "ivan.chung@buzzvil.com" },
  { nickname: "Sasha", email: "sasha.lee@buzzvil.com" },
  { nickname: "Jay", email: "jay.jeong@buzzvil.com" },
  { nickname: "Carl", email: "carl.cho@buzzvil.com" },
  { nickname: "Shannon", email: "shannon.kim@buzzvil.com" },
  { nickname: "Lucas", email: "lucas.gong@buzzvil.com" },
  { nickname: "Mella", email: "mella.min@buzzvil.com" },
  { nickname: "Nonan", email: "nonan.noh@buzzvil.com" },
  { nickname: "Woody", email: "woody.jung@buzzvil.com" },
  { nickname: "Glenn", email: "glenn.kim@buzzvil.com" },
  { nickname: "Green", email: "green.kang@buzzvil.com" },
  { nickname: "Weasley", email: "weasley.nam@buzzvil.com" },
  { nickname: "Frank", email: "frank.koh@buzzvil.com" },
  { nickname: "Elric", email: "elric.lim@buzzvil.com" },
  { nickname: "Luca", email: "luca.jung@buzzvil.com" },
  { nickname: "Lumi", email: "lumi.seo@buzzvil.com" },
  { nickname: "Nathan", email: "nathan.seo@buzzvil.com" },
  { nickname: "Edan", email: "edan.han@buzzvil.com" },
  { nickname: "Silas", email: "silas.cho@buzzvil.com" },
  { nickname: "Dorothy", email: "dorothy.yu@buzzvil.com" },
  { nickname: "Patrick", email: "patrick.park@buzzvil.com" },
  { nickname: "Wade", email: "wade.kim@buzzvil.com" },
  { nickname: "Miles", email: "miles.lee@buzzvil.com" },
  { nickname: "Watt", email: "watt.choi@buzzvil.com" },
  { nickname: "Joy", email: "joy.bae@buzzvil.com" },
  { nickname: "Silo", email: "silo.park@buzzvil.com" },
  { nickname: "Caisy", email: "caisy.son@buzzvil.com" },
  { nickname: "Edward", email: "edward.jang@buzzvil.com" },
  { nickname: "Chris", email: "chris.jung@buzzvil.com" },
  { nickname: "Jed", email: "jed.jeon@buzzvil.com" },
  { nickname: "Jeff", email: "jeff.cho@buzzvil.com" },
  { nickname: "Zen", email: "zen.kim@buzzvil.com" },
  { nickname: "Philip", email: "philip.kwun@buzzvil.com" },
  { nickname: "Allan", email: "allan.kim@buzzvil.com" },
  { nickname: "Menny", email: "menny.sim@buzzvil.com" },
  { nickname: "Jasmine", email: "jasmine.kim@buzzvil.com" },
  { nickname: "Ellie", email: "ellie.lee@buzzvil.com" },
  { nickname: "Thor", email: "thor.son@buzzvil.com" },
  { nickname: "Rina", email: "rina.lee@buzzvil.com" },
  { nickname: "Stella", email: "stella.song@buzzvil.com" },
  { nickname: "Karis", email: "karis.song@buzzvil.com" },
  { nickname: "David", email: "david.jin@buzzvil.com" },
  { nickname: "Yenny", email: "yenny.kim@buzzvil.com" },
  { nickname: "Eric", email: "eric.noh@buzzvil.com" },
  { nickname: "Wendy", email: "wendy.seo@buzzvil.com" },
  { nickname: "Brandon", email: "brandon.jang@buzzvil.com" },
  { nickname: "Aegon", email: "aegon.jang@buzzvil.com" },
  { nickname: "Isla", email: "isla.oh@buzzvil.com" },
  { nickname: "Hazard", email: "hazard.ham@buzzvil.com" },
  { nickname: "Lowen", email: "lowen.go@buzzvil.com" },
  { nickname: "Eden", email: "eden.ryu@buzzvil.com" },
  { nickname: "Silver", email: "silver.hong@buzzvil.com" },
  { nickname: "River", email: "river.kim@buzzvil.com" },
  { nickname: "Vale", email: "vale.kim@buzzvil.com" },
  { nickname: "Reina", email: "reina.jeong@buzzvil.com" },
  { nickname: "Steven", email: "steven.yang@buzzvil.com" },
  { nickname: "Romy", email: "romy.kim@buzzvil.com" },
  { nickname: "Ocean", email: "ocean.yang@buzzvil.com" },
  { nickname: "Ben", email: "ben.baek@buzzvil.com" },
  { nickname: "Liam", email: "liam.lee@buzzvil.com" },
  { nickname: "Jarrod", email: "jarrod.lee@buzzvil.com" },
  { nickname: "Alex", email: "alex.chung@buzzvil.com" },
  { nickname: "Gianna", email: "gianna.shim@buzzvil.com" },
  { nickname: "Liana", email: "liana.kim@buzzvil.com" },
  { nickname: "Zenith", email: "zenith.kim@buzzvil.com" },
  { nickname: "Tiana", email: "tiana.lee@buzzvil.com" },
];

async function main() {
  console.log("Seeding employees...");

  for (const employee of employees) {
    await prisma.user.upsert({
      where: { email: employee.email },
      update: {
        nickname: employee.nickname,
      },
      create: {
        email: employee.email,
        nickname: employee.nickname,
        emailVerified: true,
      },
    });
  }

  console.log(`Seeded ${employees.length} employees`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
